# Generated by Django 6.0.5 on 2026-05-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('habitacion', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
