# Generated by Django 6.0.5 on 2026-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservacion_alter_habitacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.URLField(max_length=500),
        ),
    ]
